#!/usr/bin/env bash

set -Eeuxo pipefail

pushd "$(dirname "$0")" >/dev/null

target="${TARGET:-web}"

rm -rf dist
wasm-pack build --target web --out-dir dist
pushd dist

jq -s '.[0] * .[1]' package.json ../package.merge.json > package.new.json
mv package.new.json package.json
popd

popd >/dev/null
