#!/usr/bin/env bash

set -Eeuxo pipefail

pushd "$(dirname "$0")" >/dev/null

target="${TARGET:-web}"

rm -rf pkg
wasm-pack build --target "$target"
pushd pkg

jq -s '.[0] * .[1]' package.json ../package.merge.json > package.new.json
mv package.new.json package.json
popd

popd >/dev/null
